<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async函数和await_捕获错误</title>
</head>
<body>
    <form>
        <span>省份：</span>
        <select>
          <option class="province"></option>
        </select>
        <span>城市：</span>
        <select>
          <option class="city"></option>
        </select>
        <span>地区：</span>
        <select>
          <option class="area"></option>
        </select>
    </form>
    <script src="https://cdn.bootcdn.net/ajax/libs/axios/1.2.0/axios.min.js"></script>
    <script>
        async function getData(){
        // 1.try包裹可能产生错误的代码
          try{
            const pObj = await axios({url:'http://hmajax.itheima.net/api/province'})
           const pname = pObj.data.list[0]
           document.querySelector('.province').innerHTML = pname

           const cObj = await axios({url:'http://hmajax.itheima.net/api/city',params:{pname:pname}})
           const cname = cObj.data.list[0]
           document.querySelector('.city').innerHTML = cname

           const aObj = await axios({url:'http://hmajax.itheima.net/api/area',params:{pname:pname,cname:cname}})
           const aname = aObj.data.list[0]
           document.querySelector('.area').innerHTML = aname
          }catch(error){
            //2.接着调用catch块,接收错误信息
            //如果try中某行代码报错后，其后面的代码不会执行
             console.dir(error)
          }
        }
        getData()
    </script>
</body>
</html>